CREATE TABLE EMPLOYEE(EMPID VARCHAR(50) PRIMARY KEY NOT NULL, EMPNAME VARCHAR(50) NOT NULL,DEPARTMENT VARCHAR(50) NOT NULL,SALARY INT NOT NULL,MANAGERID VARCHAR(50) , FOREIGN KEY (MANAGERID) REFERENCES EMPLOYEE(EMPID) );


CREATE TABLE TRAINING_COURSE(COURSEID VARCHAR(50) PRIMARY KEY , COURSENAME VARCHAR(50) NOT NULL, DURATIONHOURS INT,FEE INT );

CREATE TABLE ENROLLMENT(EMPID VARCHAR(50), COURSEID VARCHAR(50),MARKS NUMBER(3,1),ENROLLDATE DATE, PRIMARY KEY (EMPID,COURSEID),FOREIGN KEY (EMPID) REFERENCES EMPLOYEE(EMPID),FOREIGN KEY (COURSEID) REFERENCES TRAINING_COURSE(COURSEID) );


insert into employee values('E101','Ananya','it',85000,null);
insert into employee values('E102','Bharat','it',60000,'E101');
insert into employee values('E103','Charan','it',55000,'E101');
insert into employee values('E104','Divya','HR',78000,NULL);
INSERT INTO EMPLOYEE VALUES('E105','Esha','HR',50000,'E104');

SELECT * FROM ENROLLMENT;


INSERT ALL
    INTO TRAINING_COURSE VALUES ('C201', 'SQL Programming', 30, 6000)
    INTO TRAINING_COURSE VALUES ('C202', 'Python Development', 40, 8000)
    INTO TRAINING_COURSE VALUES ('C203', 'Data Analytics', 35, 10000)
SELECT * FROM dual;


INSERT INTO ENROLLMENT VALUES('E101','C203',92,DATE '2026-07-10');
INSERT INTO ENROLLMENT VALUES('E102','C201',85,DATE '2026-07-12');
INSERT INTO ENROLLMENT VALUES('E102','C202',78,DATE '2026-07-15');
INSERT INTO ENROLLMENT VALUES('E103','C201',72,DATE '2026-07-12');
INSERT INTO ENROLLMENT VALUES('E104','C202',88,DATE '2026-07-18');
INSERT INTO ENROLLMENT VALUES('E105','C201',68,DATE '2026-07-20');


SELECT * FROM ENROLLMENT;



select empname,salary from employee where department='it' and salary>55000 order by salary desc;


select department,avg(salary) from employee group by department;


select department,avg(salary) from employee group by department having avg(salary)>60000;


4

SELECT EMPLOYEE.EmpName, TRAINING_COURSE.CourseName,
       ENROLLMENT.Marks, ENROLLMENT.EnrollDate
FROM EMPLOYEE
JOIN ENROLLMENT
ON EMPLOYEE.EmpID = ENROLLMENT.EmpID
JOIN TRAINING_COURSE
ON ENROLLMENT.CourseID = TRAINING_COURSE.CourseID;




5

SELECT E1.EmpName, E2.EmpName
FROM EMPLOYEE E1
JOIN EMPLOYEE E2
ON E1.ManagerID = E2.EmpID;


6 

SELECT EMPNAME, SALARY
FROM EMPLOYEE
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM EMPLOYEE
);



samplep
123
